config/routes.rb
    resource :creatorships, controller: "creatorships", only: [:show, :update]
    resources :external_authors do
      resources :external_author_names
    end
    resources :favorite_tags, only: [:create, :destroy]
    resources :gifts, only: [:index]
    resource :inbox, controller: "inbox" do
      member do
        get :reply
        post :delete
      end
    end
    resources :invitations do
      collection do
        post :invite_friend
      end
      collection do
        get :manage
      end
    end
    resources :nominations, controller: "tag_set_nominations", only: [:index]
    resources :preferences, only: [:index, :update]
    resource :profile, only: [:show], controller: "profile"
    resources :pseuds do
      resources :works
      resources :series
      resources :bookmarks
    end
    resources :readings do
      collection do
        post :clear
      end
    end
    resources :related_works
    resources :series do
      member do
        get :manage
      end
      resources :serial_works
    end
    resources :signups, controller: "challenge_signups", only: [:index]
    resources :skins, only: [:index]
    resources :stats, only: [:index]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :tag_sets, controller: "owned_tag_sets", only: [:index]
    resources :works do
      collection do
        get :drafts
        get :collected
        get :show_multiple
        post :edit_multiple
        patch :update_multiple
        post :delete_multiple
      end
    end
    namespace :blocked do
      resources :users, only: [:index, :create, :destroy] do
        collection do
          get :confirm_block
        end
        member do
          get :confirm_unblock
        end
      end
    end
    namespace :muted do
      resources :users, only: [:index, :create, :destroy] do
        collection do
          get :confirm_mute
        end
        member do
          get :confirm_unmute
        end
      end
    end
  end

  resources :works do
    collection do
      post :import
      get :search
    end
    member do
      get :preview
      post :post
      put :post_draft
      get :navigate
      get :edit_tags
      get :preview_tags
      patch :update_tags
      get :mark_for_later
      get :mark_as_read
      get :confirm_delete
      get :share
    end
    resources :bookmarks
    resources :chapters do
      collection do
        get :manage
        post :update_positions
      end
      member do
        get :preview
        post :post
        get :confirm_delete
      end
      resources :comments
    end
    resources :collections
    resources :collection_items
    resources :comments do
      member do
        put :approve
        put :reject
      end
      collection do
        get :unreviewed
        put :review_all
      end
    end
    resource :hit_count, controller: :hit_count, only: [:create]
    resources :kudos, only: [:index]
    resources :links, controller: "work_links", only: [:index]
    resource :troubleshooting, controller: :troubleshooting, only: [:show, :update]
  end

  resources :chapters do
    member do
      get :preview
      post :post
    end
    resources :comments
  end

  resources :external_works do
    collection do
      get :fetch
    end
    resources :bookmarks
    resources :related_works
  end

  resources :related_works
  resources :serial_works
  resources :series do
    member do
      get :confirm_delete
      get :manage
      post :update_positions
    end
    resources :bookmarks
  end

  resources :gifts, only: [:index] do
    member do
      post :toggle_rejected
    end
  end

  resources :collections do
    collection do
      get :list_challenges
      get :list_ge_challenges
      get :list_pm_challenges
    end
    member do
      get :confirm_delete
    end
    resource :profile, controller: "collection_profile"
    resources :collections
    resources :works
    resources :gifts
    resources :bookmarks
    resources :media
    resources :fandoms
    resources :people
    resources :prompts
    resources :tags do
      resources :works
    end
    resources :participants, controller: "collection_participants", only: [:index, :update, :destroy] do
      collection do
        get :add
        get :join
      end
    end
    resources :items, controller: "collection_items" do
      collection do
        patch :update_multiple
      end
    end
    resources :signups, controller: "challenge_signups" do
      collection do
        get :summary
      end
      member do
        get :confirm_delete
      end
    end
    resources :assignments, controller: "challenge_assignments", only: [:index, :show] do
      collection do
        get :confirm_purge
        get :generate
        put :set
        post :purge
        get :send_out
        put :update_multiple
        get :default_all
      end
      member do
        get :default
      end
    end
    resources :claims, controller: "challenge_claims" do
      collection do
        patch :set
        get :purge
      end
    end
    resources :potential_matches do
      collection do
        get :generate
        get :cancel_generate
        get :regenerate_for_signup
      end
    end
    resources :requests, controller: "challenge_requests"
    resource :gift_exchange, controller: "challenge/gift_exchange" do
      member do
        get :confirm_delete
      end
    end
    resource :prompt_meme, controller: "challenge/prompt_meme" do
      member do
        get :confirm_delete
      end
    end
  end

  resources :languages do
    resources :works
    resources :admin_posts
  end
  resources :locales, except: :destroy

  namespace :api do
    namespace :v2 do
      resources :bookmarks, only: [:create], defaults: { format: :json }
      resources :works, only: [:create], defaults: { format: :json }
      post 'bookmarks/search', to: 'bookmarks#search'
      post 'works/search', to: 'works#search'
    end
  end

  resources :comments do
    member do
      put :approve
      put :freeze
      put :hide
      put :reject
      put :review
      put :unfreeze
      put :unhide
    end
    collection do
      get :hide_comments
      get :show_comments
      get :add_comment_reply
      get :cancel_comment_reply
      get :cancel_comment_edit
      get :delete_comment
      get :cancel_comment_delete
    end
    resources :comments
  end
  resources :bookmarks do
    collection do
      get :search
    end
    member do
      get :confirm_delete
      get :share
    end
    resources :collection_items
  end

  resources :kudos, only: [:create]

  resources :skins do
    member do
      get :preview
      get :set
      get :confirm_delete
    end
    collection do
      get :unset
    end
  end
  resources :known_issues
  resources :archive_faqs, path: "faq" do
    member do
      get :confirm_delete
    end
    collection do
      get :manage
      post :update_positions
    end
    resources :questions do
      collection do
        get :manage
        post :update_positions
      end
    end
  end
  resources :wrangling_guidelines do
    member do
      get :confirm_delete
    end
    collection do
      get :manage
      post :update_positions
    end
  end

  resource :redirect, controller: "redirect", only: [:show] do
    member do
      get :do_redirect
    end
  end

  resources :abuse_reports, only: [:new, :create]
  resources :external_authors do
    resources :external_author_names
  end
  resources :orphans, only: [:index, :new, :create]

  get 'search' => 'works#search'
  post 'support' => 'feedbacks#create', as: 'feedbacks'
  get 'support' => 'feedbacks#new', as: 'new_feedback_report'
  get 'tos' => 'home#tos'
  get 'tos_faq' => 'home#tos_faq'
  get 'unicorn_test' => 'home#unicorn_test'
  get 'dmca' => 'home#dmca'
  get 'diversity' => 'home#diversity'
  get 'site_map' => 'home#site_map'
  get 'site_pages' => 'home#site_pages'
  get 'first_login_help' => 'home#first_login_help'
  get 'token_dispenser' => 'home#token_dispenser'
  get 'delete_confirmation' => 'users#delete_confirmation'
  get 'activate/:id' => 'users#activate', as: 'activate'
  get 'devmode' => 'devmode#index'
  get 'donate' => 'home#donate'
  get 'lost_cookie' => 'home#lost_cookie'
  get 'about' => 'home#about'
  get 'menu/browse' => 'menu#browse'
  get 'menu/fandoms' => 'menu#fandoms'
  get 'menu/search' => 'menu#search'
  get 'menu/about' => 'menu#about'

  root to: "home#index"

  get '/bookmarks/fetch_recent/:id' => 'bookmarks#fetch_recent', as: :fetch_recent_bookmarks
  get '/bookmarks/hide_recent/:id' => 'bookmarks#hide_recent', as: :hide_recent_bookmarks

  get '/invite_requests/show' => 'invite_requests#show', as: :show_invite_request
  get '/user_invite_requests/update' => 'user_invite_requests#update'

  patch '/admin/skins/update' => 'admin_skins#update', as: :update_admin_skin

  get "/admin/admin_users/troubleshoot/:id" => "admin/admin_users#troubleshoot", as: :troubleshoot_admin_user

  %w[
    pseud
    tag
    fandom
    character
    relationship
    freeform
    character_in_fandom
    relationship_in_fandom
    tags_in_sets
    associated_tags
    noncanonical_tag
    collection_fullname
    open_collection_names
    collection_parent_name
    external_work
    potential_offers
    potential_requests
    owned_tag_sets
    site_skins
    admin_posts
    admin_post_tags
  ].each do |action|
    get "/autocomplete/#{action}" => "autocomplete##{action}"
  end

  get '/challenges/no_collection' => 'challenges#no_collection'
  get '/challenges/no_challenge' => 'challenges#no_challenge'

  get '/works/clean_work_search_params' => 'works#clean_work_search_params'
  get '/works/collected' => 'works#collected'
  get '/works/drafts' => 'works#drafts'

  post '/works/edit_multiple/:id' => 'works#edit_multiple'
  post '/works/confirm_delete_multiple/:id' => 'works#confirm_delete_multiple'
  post '/works/delete_multiple/:id' => 'works#delete_multiple'

app/models/locale.rb
class Locale < ApplicationRecord
  belongs_to :language
  validates_presence_of :iso
  validates :iso, uniqueness: true
  validates_presence_of :name

  scope :default_order, -> { order(:iso) }

  def to_param
    iso
  end

  def self.default
    language = Language.default
    Locale.set_base_locale(iso: ArchiveConfig.DEFAULT_LOCALE_ISO, name: ArchiveConfig.DEFAULT_LOCALE_NAME, language_id: language.id)
  end

  def self.set_base_locale(locale={iso: "en", name: "English"})
    language = Language.find_by(short: ArchiveConfig.DEFAULT_LANGUAGE_SHORT)
    Locale.find_by(iso: locale[:iso].to_s) || language.locales.create(iso: locale[:iso].to_s, name: locale[:name].to_s, main: 1)
  end

  after_update :update_translations, if: :saved_change_to_iso?
  def update_translations
    ArchiveFaq::Translation.where(locale: iso_before_last_save).update_all(locale: iso)
    Question::Translation.where(locale: iso_before_last_save).update_all(locale: iso)
  end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  def index
    authorize Locale

    @locales = Locale.default_order
  end

  def new
    @locale = Locale.new
    authorize @locale
    @languages = Language.default_order
  end

  # GET /locales/en/edit
  def edit
    @locale = Locale.find_by(iso: params[:id])
    authorize @locale
    @languages = Language.default_order
  end

  def update
    @locale = Locale.find_by(iso: params[:id])
    @locale.attributes = locale_params
    authorize @locale
    if @locale.save
      flash[:notice] = ts('Your locale was successfully updated.')
      redirect_to action: 'index', status: 303
    else
      @languages = Language.default_order
      render action: "edit"
    end
  end


  def create
    @locale = Locale.new(locale_params)
    authorize @locale
    if @locale.save
      flash[:notice] = t('successfully_added', default: 'Locale was successfully added.')
      redirect_to locales_path
    else
      @languages = Language.default_order
      render action: "new"
    end
  end

  private

  def locale_params
    params.require(:locale).permit(
      :name, :iso, :language_id, :email_enabled, :interface_enabled
    )
  end
end

app/views/locales/_locale_form.html.erb
<%= form_for(@locale, html: { class: 'post' }) do |f| %>
  <p class="required notice">* <%= t('.required_notice', :default => "Required information") %></p>
  
  <fieldset>
    <legend><%= t('.locale_legend', :default => "Locale") %></legend>
    <h3 class="landmark heading"><%= t('.locale_heading', :default => "Locale") %></h3>
    <dl>
      <dt class="required"><%= f.label :name, t('.name', :default => "Name") + '*' %></dt>
      <dd class="required"><%= f.text_field :name %></dd>

      <dt class="required"><%= f.label :iso, t('.iso', :default => "ISO code") + '*' %></dt>
      <dd class="required"><%= f.text_field :iso %></dd>

      <dt class="required"><%= f.label :language_id, t('.language', :default => "Language") + '*' %></dt>
      <dd class="required"><%= f.select(:language_id, @languages.collect { |language| [ language.name, language.id ] }) %></dd>

      <dt><%= f.check_box :email_enabled %></dt>
      <dd><%= f.label :email_enabled, t('.enable_email', :default => "Use this locale to send email") %></dd>

      <dt><%= f.check_box :interface_enabled %></dt>
      <dd><%= f.label :interface_enabled, t('.enable_interface', :default => "Use this locale for the interface") %></dd>

    </dl>
  </fieldset>
  <fieldset>
    <legend><%= t('.actions_legend', :default => "Actions") %></legend>
    <h3 class="landmark heading"><%= t('.actions_heading', :default => "Actions") %></h3>
    <p class="submit actions">
      <%= f.submit @locale.new_record? ? t('.create_button', :default => "Create Locale") : t('.edit_button', :default => "Update Locale") %>
    </p>
  </fieldset>
<% end %>

app/views/locales/_navigation.html.erb
<ul class="navigation actions" role="navigation">
  <li><%= span_if_current t('.link_to_index', :default => 'Locales'), locales_path %></li>
  <li><%= span_if_current t('.link_to_new', :default => 'New Locale'), new_locale_path %></li>
</ul>

app/views/locales/edit.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= t('.edit_locale', :default => 'Edit Locale') %></h2>
<%= error_messages_for :locale %>
<!--/descriptions-->

<!--subnav-->
<%= render 'navigation' %>
<!--/subnav-->

<!--main content-->
<%= render 'locale_form' %>
<!--/content-->

app/views/locales/index.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= t('.supported_locales', :default => 'Supported Locales') %></h2>
<!--/descriptions-->

<!--main content-->
<%= render 'navigation' %>
<!--main content-->
<table summary="<%= t('.locale_table_summary', :default => 'Lists supported locales, along with details of how they are used and options to modify them.') %>">
  <caption><%= t('.locale_table_caption', :default => 'Supported Locales') %></caption>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">ISO Code</th>
      <th scope="col">Primary Locale</th>
      <th scope="col">Use for Email</th>
      <th scope="col">Use for Interface</th>
      <th scope="col">Created at</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% for locale in @locales %>
      <tr>
        <th scope="row"><%= locale.name %></th>
        <td><%= locale.iso %></td>
        <td><%= locale.main %></td>
        <td><%= locale.email_enabled %></td>
        <td><%= locale.interface_enabled %></td>
        <td><%= locale.updated_at %></td>
        <td class="actions">
          <%= link_to ts('Edit'), {controller: :locales, action: :edit, id: locale.iso} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--/content-->

<!--subnav-->
<!--/subnav-->

app/views/locales/new.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= t('.add_new_locale', :default => 'New Locale') %></h2>
<%= error_messages_for :locale %>
<!--/descriptions-->

<!--subnav-->
<%= render 'navigation' %>
<!--/subnav-->

<!--main content-->
<%= render 'locale_form' %>
<!--/content-->