config/routes.rb
Otwarchive::Application.routes.draw do

  devise_scope :admin do
    get "admin/logout" => "admin/sessions#confirm_logout"

    put "admin/password/reset" => "admin/passwords#update"
  end

  devise_for :admin,
             module: "admin",
             only: [:sessions, :passwords],
             controllers: {
               sessions: "admin/sessions",
               passwords: "admin/passwords"
             },
             path_names: {
               sign_in: "login",
               sign_out: "logout"
             }

  devise_scope :user do
    get "signup(/:invitation_token)" => "users/registrations#new", as: "signup"
    get "users/logout" => "users/sessions#confirm_logout"

    put "users/password/reset" => "users/passwords#update"
  end

  devise_for :users,
             module: "users",
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations",
               passwords: "users/passwords"
             },
             path_names: {
               sign_in: "login",
               sign_out: "logout"
             }

  get '/403', to: 'errors#403'
  get '/404', to: 'errors#404'
  get '/422', to: 'errors#422'
  get '/500', to: 'errors#500'
  get '/auth_error', to: 'errors#auth_error'

  get 'downloads/:id/:download_title.:format' => 'downloads#show', as: 'download'

  namespace :opendoors do
    resources :tools, only: [:index] do
      collection do
        post :url_update
      end
    end
    resources :external_authors do
      member do
        post :forward
      end
    end
  end

  resources :invitations
  resources :user_invite_requests
  resources :invite_requests, only: [:index, :create, :destroy] do
    collection do
      get :manage
      get :status
    end
  end

  get 'claim/:invitation_token' => 'external_authors#claim', as: 'claim'
  post 'complete_claim/:invitation_token' => 'external_authors#complete_claim', as: 'complete_claim'

  resources :media do
    resources :fandoms
  end
  resources :fandoms do
    collection do
      get :unassigned
    end
    get :show
  end
  resources :tag_wranglings do
    collection do
      post :wrangle
    end
  end
  resources :tag_wranglers
  resources :unsorted_tags do
    collection do
      post :mass_update
    end
  end
  resources :tags do
    member do
      get :feed
      post :mass_update
      get :remove_association
      get :wrangle
    end
    collection do
      get :show_hidden
      get :search
    end
    resources :works
    resources :bookmarks
    resources :comments
    resource :troubleshooting, controller: :troubleshooting, only: [:show, :update]
  end

  resources :tag_sets, controller: 'owned_tag_sets' do
    resources :nominations, controller: 'tag_set_nominations' do
      collection do
        put :update_multiple
        delete :destroy_multiple
        get :confirm_destroy_multiple
      end
      member do
        get :confirm_delete
      end
    end
    resources :associations, controller: 'tag_set_associations', only: [:index] do
      collection do
        put :update_multiple
      end
    end
    member do
      get :batch_load
      put :do_batch_load
      get :confirm_delete
    end
    collection do
      get :show_options
    end
  end
  resources :tag_nominations, only: [:update]

  resources :tag_wrangling_requests, only: [:index] do
    collection do
      patch :update_multiple
    end
  end

  resources :admin_posts do
    resources :comments
  end

  namespace :admin do
    resources :activities, only: [:index, :show]
    resources :banners do
      member do
        get :confirm_delete
      end
    end
    resources :blacklisted_emails, only: [:index, :create, :destroy]
    resources :settings
    resources :skins do
      collection do
        get :index_rejected
        get :index_approved
      end
    end
    resources :spam, only: [:index] do
      collection do
        post :bulk_update
      end
    end
    resources :user_creations, only: [:destroy] do
      member do
        put :hide
        put :set_spam
      end
    end
    resources :users, controller: "admin_users", only: [:index, :show] do
      member do
        get :confirm_delete_user_creations
        post :destroy_user_creations
        post :activate
        post :send_activation
        get :check_user
      end
      collection do
        get :bulk_search
        post :bulk_search
        post :update
        post :update_status
        post :update_next_of_kin
      end
    end
    resources :invitations, controller: 'admin_invitations' do
      collection do
        post :invite_from_queue
        post :grant_invites_to_users
        get :find
      end
    end
    resources :api
  end
  resources :admins, only: [:index]

  post '/admin/api/new', to: 'admin/api#create'

  resources :people, only: [:index] do
    collection do
      get :search
    end
  end

  resources :users, except: [:new, :create] do
    member do
      get :change_email
      post :changed_email
      get :change_password
      post :changed_password
      get :change_username
      post :changed_username
      post :end_first_login
      post :end_banner
      post :end_tos_prompt
    end
    resources :assignments, controller: "challenge_assignments", only: [:index]
    resources :claims, controller: "challenge_claims", only: [:index]
    resources :bookmarks
    resources :collection_items, only: [:index, :update] do
      collection do
        patch :update_multiple
      end
    end
    resources :collections, only: [:index]
    resources :comments do
      member do
        put :approve
        put :reject
      end
    end
    resource :creatorships, controller: "creatorships", only: [:show, :update]
    resources :external_authors do
      resources :external_author_names
    end
    resources :favorite_tags, only: [:create, :destroy]
    resources :gifts, only: [:index]
    resource :inbox, controller: "inbox" do
      member do
        get :reply
        post :delete
      end
    end
    resources :invitations do
      collection do
        post :invite_friend
      end
      collection do
        get :manage
      end
    end
    resources :nominations, controller: "tag_set_nominations", only: [:index]
    resources :preferences, only: [:index, :update]
    resource :profile, only: [:show], controller: "profile"
    resources :pseuds do
      resources :works
      resources :series
      resources :bookmarks
    end
    resources :readings do
      collection do
        post :clear
      end
    end
    resources :related_works
    resources :series do
      member do
        get :manage
      end
      resources :serial_works
    end
    resources :signups, controller: "challenge_signups", only: [:index]
    resources :skins, only: [:index]
    resources :stats, only: [:index]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :tag_sets, controller: "owned_tag_sets", only: [:index]
    resources :works do
      collection do
        get :drafts
        get :collected
        get :show_multiple
        post :edit_multiple
        patch :update_multiple
        post :delete_multiple
      end
    end
    namespace :blocked do
      resources :users, only: [:index, :create, :destroy] do
        collection do
          get :confirm_block
        end
        member do
          get :confirm_unblock
        end
      end
    end
    namespace :muted do
      resources :users, only: [:index, :create, :destroy] do
        collection do
          get :confirm_mute
        end
        member do
          get :confirm_unmute
        end
      end
    end
  end

  resources :works do
    collection do
      post :import
      get :search
    end
    member do
      get :preview
      post :post
      put :post_draft
      get :navigate
      get :edit_tags
      get :preview_tags
      patch :update_tags
      get :mark_for_later
      get :mark_as_read
      get :confirm_delete
      get :share
    end
    resources :bookmarks
    resources :chapters do
      collection do
        get :manage
        post :update_positions
      end
      member do
        get :preview
        post :post
        get :confirm_delete
      end
      resources :comments
    end
    resources :collections
    resources :collection_items
    resources :comments do
      member do
        put :approve
        put :reject
      end
      collection do
        get :unreviewed
        put :review_all
      end
    end
    resource :hit_count, controller: :hit_count, only: [:create]
    resources :kudos, only: [:index]
    resources :links, controller: "work_links", only: [:index]
    resource :troubleshooting, controller: :troubleshooting, only: [:show, :update]
  end

  resources :chapters do
    member do
      get :preview
      post :post
    end
    resources :comments
  end

  resources :external_works do
    collection do
      get :fetch
    end
    resources :bookmarks
    resources :related_works
  end

  resources :related_works
  resources :serial_works
  resources :series do
    member do
      get :confirm_delete
      get :manage
      post :update_positions
    end
    resources :bookmarks
  end

  resources :gifts, only: [:index] do
    member do
      post :toggle_rejected
    end
  end

  resources :collections do
    collection do
      get :list_challenges
      get :list_ge_challenges
      get :list_pm_challenges
    end
    member do
      get :confirm_delete
    end
    resource :profile, controller: "collection_profile"
    resources :collections
    resources :works
    resources :gifts
    resources :bookmarks
    resources :media
    resources :fandoms
    resources :people
    resources :prompts
    resources :tags do
      resources :works
    end
    resources :participants, controller: "collection_participants", only: [:index, :update, :destroy] do
      collection do
        get :add
        get :join
      end
    end

app/views/tags/_search_form.html.erb
<%= form_for @search, as: :tag_search, url: search_tags_path, html: { class: "search", method: :get } do |f| %>
  <fieldset>
    <dl>
      <dt>
        <%= f.label :name, ts("Tag name") %>
        <%= link_to_help "tag-search-text-help" %>
      </dt>
      <dd>
        <%= f.text_field :name %>
      </dd>
      <dt>
        <%= f.label :fandoms, ts("Fandoms") %>
      </dt>
      <dd>
        <%= f.text_field :fandoms, autocomplete_options("fandom", "aria-describedby" => "fandom-field-description") %>
        <p class="footnote" id="fandom-field-description">
          <%= ts("Find tags wrangled to specific canonical fandoms.") %>
        </p>
      </dd>
      <dt><%= ts("Type") %></dt>
      <dd>
        <fieldset>
          <ul>
            <% types = Tag::USER_DEFINED %>
            <% types.each do |type| %>
              <li>
                <%= f.radio_button :type, type %>
                <%= f.label :type, ts("%{type}", type: type), value: type %>
              </li>
            <% end %>
            <li>
              <%= f.radio_button :type, "" %>
              <%= f.label :type, ts("Any type"), value: "" %>
            </li>
          </ul>
        </fieldset>
      </dd>
      <dt><%= ts("Wrangling status") %></dt>
      <dd>
        <fieldset>
          <ul>
            <li>
              <%= f.radio_button :canonical, "T" %>
              <%= f.label :canonical, ts("Canonical"), value: "T" %>
            </li>
            <li>
              <%= f.radio_button :canonical, "F" %>
              <%= f.label :canonical, ts("Non-canonical"), value: "F" %>
            </li>
            <li>
              <%= f.radio_button :canonical, "" %>
              <%= f.label :canonical, ts("Any status"), value: "" %>
            </li>
          </ul>
        </fieldset>
      <dt>
        <%= f.label :sort_column, ts("Sort by") %>
      </dt>
      <dd>
        <%= f.select :sort_column, options_for_select(@search.sort_options, @search.sort_column) %>
      </dd>
      <dt>
        <%= f.label :sort_direction, ts("Sort direction") %>
      </dt>
      <dd>
        <%= f.select :sort_direction,
          options_for_select([["Ascending", "asc"], ["Descending", "desc"]], @search.sort_direction) %>
      </dd>
    </dl>
    <p class="submit actions"><%= f.submit ts("Search Tags") %></p>
  </fieldset>
<% end %>

app/views/tags/index.html.erb
<!--SEARCHBROWSE-->
<!--Descriptive page names, messages and instructions-->
<h2 class="heading"><%= ts("Tags") %></h2>
<!--/descriptions-->

<!--subnav-->
<% unless @collection %>
  <ul class="navigation actions" role="navigation">
    <% if logged_in? %><li><%= link_to ts("Tag Sets"), tag_sets_path %></li><% end %>
    <li><%= span_if_current(ts('Most Popular'), tags_path, params[:show].blank?) %></li>
    <li><%= span_if_current ts('Random'), tags_path(:show => "random") %></li>
  </ul>
<% end %>
<!--/subnav-->

<!--main content-->
<% unless @collection %>
  <h3 class="landmark heading">
    <% if params[:show] == "random" %>
      <%= ts('Browse Random Tags')%>
    <% else %>
      <%= ts('Browse Popular Tags')%>
    <% end %>
  </h3>
<% end %>

<% if @tags %>
  <% if params[:show] == "random" %>
    <% if @collection %>
      <p><%= t(".about.random_in_collection") %></p>
    <% else %>
      <p><%= t(".about.random", search_tags_link: (link_to t(".search_tags"), search_tags_path)).html_safe %></p>
    <% end %>
  <% else %>
    <% if @collection %>
      <p><%= t(".about.popular_in_collection") %></p>
    <% else %>
      <p><%= t(".about.popular", search_tags_link: (link_to t(".search_tags"), search_tags_path)).html_safe %></p>
    <% end %>
  <% end %>
  <ul class="tags cloud index group">
    <!--FRONT END REVIEW: these classes are irregular-->
    <% tag_cloud @tags, %w(cloud1 cloud2 cloud3 cloud4 cloud5 cloud6 cloud7 cloud8) do |tag, css_class| %>
      <li><%= link_to_tag_works(tag, class: css_class.dup, collection: @collection) %></li>
    <% end %>
  </ul>
<% end %>
<!--/content-->

app/views/tags/new.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= ts('New Tag') %></h2>

<%= error_messages_for :tag %>

<p><%= ts('Once you have created the tag, the attributes that are particular for that tag category will be available for editing.') %></p>

<!--/descriptions-->

<!--subnav-->
<!--/subnav-->

<!--main content-->
<%= form_for @tag, as: :tag, url: { action: "create" }  do |f| %>
  <dl>
    <dt><%= f.label :name, ts('Name') %></dt>
    <dd><%= f.text_field :name, size: ArchiveConfig.TAG_MAX %></dd>

    <dt><%= f.label :canonical, ts('Canonical') %></dt>
    <dd><%= f.check_box :canonical %></dd>

    <dt><%= ts('Category') %></dt>
    <dd>
      <% if logged_in_as_admin? %>
        <% types = Tag::TYPES  %>
      <% else %>
        <% types = Tag::USER_DEFINED %>
      <% end %>
      <ul>
        <% types.each do |type| %>
          <li>
            <%= f.radio_button("type", type) %>
            <%= f.label("type_#{type.downcase}", ts("%{type}", type: tag_type_label_name(type))) %>
          </li>
        <% end %>
      </ul>
    </dd>
  </dl>

  <p class="submit actions">
    <%= f.submit %>
  </p>
<% end %>
<!--/content-->

<!--subnav-->
<!--/subnav-->

app/views/tags/search.html.erb
<h2 class="heading"><%= ts("Tag Search") %></h2>

<%= render 'shared/search_nav' %>

<%= render :partial => 'tags/search_form' %>

<% if @tags %>
  <h3 class="heading"><%= search_results_found(@tags) %> <%= link_to_help "tag-search-results-help" %></h3>
  <h4 class="landmark heading">Listing Tags</h4>
  <ol class="tag index group">
    <% for tag in @tags %>
      <% unless tag.nil? %>
        <li><%= tag_search_result(tag) %></li>
      <% end %>
    <% end %>
  </ol>
  <%= will_paginate @tags %>
<% end %>

app/views/tags/show.html.erb
<!--ZONES TAG HOME Descriptive page name, messages and instructions-->
<div class="tag home profile">
  <div class="primary header module">
    <h2 class="heading"><%= @tag.name %></h2>
    <div class="icon"></div>
    <% if @tag.canonical || @tag.merger || can_wrangle? %>
      <ul class="navigation actions" role="navigation">
        <% if @tag.canonical || @tag.merger %>
          <li><%= link_to ts('Works'), {:controller => :works, :action => :index, :tag_id => @tag} %></li>
          <li><%= link_to ts('Bookmarks'), {:controller => :bookmarks, :action => :index, :tag_id => @tag} %></li>
        <% end %>
    	<% if can_wrangle? %>
      	  <li><%= link_to ts('Edit'), {:controller => :tags, :action => :edit, :id => @tag} %> </li>
      	  <li><%= tag_comment_link(@tag) %></li>
          <li class="reindex"><%= link_to ts("Troubleshoot"), tag_troubleshooting_path(@tag) %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= error_messages_for :tag %>
  <!--/descriptions-->

  <!--main content-->
  <p><%= ts("This tag belongs to the %{tag_class} Category.", :tag_class => @tag.class::NAME) %>
  <% if @tag.canonical %>
    <%= ts("It's a common tag. You can use it to ") %> 
    <%= link_to ts('filter works'), {:controller => :works, :action => :index, :tag_id => @tag} %> <%= ts('and to') %> 
    <%= link_to ts('filter bookmarks'), {:controller => :bookmarks, :action => :index, :tag_id => @tag} %>.
  <% end %>
  </p>
  

  <% if @tag.is_a?(Rating) && @tag.adult %>
  <p class="warning"><%= ts('This tag indicates adult content.') %></p>
  <% end %>

  <% if @tag.is_a?(Fandom) %>
  <div class="parent fandom listbox group">
	  <h3 class="heading"><%= ts('Parent tags (more general)') %>:</h3>
    <ul class="tags commas index group">
	  <% (@tag.parents + [@tag.media]).uniq.compact.sort.each do |parent| %>
      <li><%= link_to_tag parent %></li>
    <% end %>
    </ul>
  </div>
  <% else %>
    <% unless @tag.parents.blank? %>
    <div class="parent listbox group">
      <h3 class="heading"><%= ts('Parent tags (more general)') %>:</h3>
      <ul class="tags commas index group"><%= tag_link_list(@tag.parents.sort) %></ul>
    </div>
    <% end %>
  <% end %>

  <% if @tag.merger %>
  <div class="merger module">
    <h3 class="heading"><%= ts("Mergers") %></h3>
    <p><%= ts("%{tag_name} has been made a synonym of %{tag_synonym_link}. Works and bookmarks tagged with %{tag_name} will show up in %{tag_synonym}'s filter.", :tag_name => @tag.name, :tag_synonym_link => (link_to_tag @tag.merger), :tag_synonym => @tag.merger.name).html_safe %></p>
  </div>
  <% end %>

  <% unless @tag_children['Merger'].blank? %>
  <div class="synonym listbox group">
    <h3 class="heading"><%= ts('Tags with the same meaning') %>:</h3>
    <ul class="tags commas index group"><%= tag_link_list(@tag_children['Merger'].sort) %></ul>
  </div>
  <% end %>

  <% unless @tag.direct_meta_tags.blank? %>
  <div class="meta listbox group">
    <h3 class="heading"><%= ts('Metatags') %>:</h3>
    <% cache "tag-#{@tag.cache_key}-metatags-v2", expires_in: 24.hours, skip_digest: true do %>
      <%= meta_tag_tree(@tag) %>
    <% end %>
  </div>
  <% end %>

  <% unless @tag.direct_sub_tags.blank? %>
  <div class="sub listbox group">
    <h3 class="heading"><%= ts('Subtags') %>:</h3>
    <% cache "tag-#{@tag.cache_key}-subtags-v2", expires_in: 24.hours, skip_digest: true do %>
      <%= sub_tag_tree(@tag) %>
    <% end %>
  </div>
  <% end %>

  <% unless (@tag_children.keys - ['Merger']).blank? %>
    <!-- caching -->
    <% cache("tag-#{@tag.cache_key}-children-v3", skip_digest: true) do %>
      <div class="child listbox group">
        <h3 class="heading"><%= ts('Child tags (displaying the first %{count} of each type)', :count => ArchiveConfig.TAG_LIST_LIMIT) %>:</h3>
        <% %w(Character Relationship Freeform).each do |type| %>
          <% if @tag_children[type].present? %>
            <div class="<%= type.to_s.pluralize.downcase %> listbox group">
              <h4 class="heading"><%= type.constantize::NAME.pluralize %>:</h4>
              <ul class="tags commas index group">
                <%= tag_link_list(@tag_children[type].sort) %>
                <% if @tag_children[type].length > ArchiveConfig.TAG_LIST_LIMIT %>
                  <li><%= ts("and more") %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if @works %>
    <p><%= ts("This tag has not been marked common and can't be filtered on (yet).") %></p>  
    <% unless @works.blank? %>
      <div class="work listbox group">
      <h3 class="heading"><%= ts('Works which have used it as a tag') %>:</h3>
      <%= paginated_section @works do %>
          <ul class="index group">
            <% for work in @works %>
              <%= render :partial => 'works/work_blurb', :locals => {:work => work} %>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% end %>

    <% unless @bookmarks.blank? %>
    <div class="bookmark listbox group">
    <h3 class="heading"><%= ts('Bookmarks which have used it as a tag') %>:</h3>
    <%= paginated_section @bookmarks, {:previous_label => '&laquo; Previous', :next_label => 'Next &raquo;'} do %>
        <ul class="index group">
          <% for bookmark in @bookmarks %>
            <%= render 'bookmarks/bookmark_blurb', :bookmark => bookmark %>
          <% end %>
        </ul>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>
<!--/content-->

app/views/tags/show_hidden.js.erb
<%
last_tag = @display_tags.last
if @display_category == 'warnings'
  open_tags = "<li class=\"#{@display_category}\"><strong>"
  closing_tags = "</strong></li>"
else
  open_tags = "<li class=\"#{@display_category}\">"
  closing_tags = "</li>"
end
tag_list = @display_tags.map {|tag| open_tags + link_to_tag_works(tag) + closing_tags }
%>
$j("#<%= "#{@display_creation.class.to_s.underscore}_#{@display_creation.id}_category_#{@display_category}" %>").replaceWith("<%= escape_javascript(tag_list.join(" ").html_safe) %>");